💚 Modify the display content of "Enable Corepack" job

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -131,13 +131,50 @@ jobs:
       - name: Enable Corepack (Automatically setup a package manager for Node.js)
         shell: bash
         run: |
-          if type corepack >/dev/null 2>&1; then
-            echo '::group::$' corepack enable
-            corepack enable
-            echo '::endgroup::'
+          exec_with_debug() {
+            local quoted_args=() apos="'" quot='"'
 
-            echo '::group::$' corepack enable npm
-            corepack enable npm
+            for arg in "$@"; do
+              # If the argument is an empty string or contains spaces or special characters, wrap it in quotes.
+              case "${arg}" in
+                '' | *[' !$&()*;<>?[\]`{|}~'"${apos}${quot}"]* )
+                  case "${arg}" in
+                    # These characters cannot be wrapped in double quotes:
+                    # - !
+                    # - $
+                    # - \
+                    # - `
+                    # - "
+                    *['!$\`'"${quot}"]* )
+                      # see https://qiita.com/kawaz/items/f8d68f11d31aa3ea3d1c
+                      quoted_args+=("${apos}${arg//${apos}/${apos}${quot}${apos}${quot}${apos}}${apos}")
+                      ;;
+                    # Other characters can be wrapped in double quotes,
+                    # so arguments containing single quotes should be wrapped in double quotes.
+                    *"${apos}"* )
+                      quoted_args+=("${quot}${arg}${quot}")
+                      ;;
+                    # Arguments not containing single quotes are wrapped in single quotes.
+                    # Single-quote escaping is not required under this condition.
+                    * )
+                      quoted_args+=("${apos}${arg}${apos}")
+                      ;;
+                  esac
+                  ;;
+                * )
+                  quoted_args+=("${arg}")
+                  ;;
+              esac
+            done
+
+            echo '[command]' "${quoted_args[*]}" >&2
+            "$@"
+          }
+
+          if type corepack >/dev/null 2>&1; then
+            echo '::group::' Enable Corepack
+            exec_with_debug corepack enable
+            exec_with_debug corepack enable npm
             echo '::endgroup::'
           fi
 
@@ -146,17 +183,26 @@ jobs:
           #       You can see what I did here: https://github.com/sounisi5011/package-version-git-tag/compare/24791b6ddab5cd2b8fdc735855556640746cc863~1...349c11acb35cfc0096bc6e9324bd9748e429ca17~1
           packageManager="$(< "${GITHUB_WORKSPACE}/package.json" jq --raw-output '.packageManager')"
           if [[ "${packageManager}" == 'npm@'* && "npm@$(npm --version)" != "${packageManager%%+*}" ]]; then
+            echo '[warning] Failed to enable Corepack'
+            echo '::group::' Install the specified npm manually
+
             # Disable the built-in Corepack in GitHub Actions.
             # If enabled, problems will occur when the yarn command is executed.
             if type corepack >/dev/null 2>&1; then
-              echo '::group::$' corepack disable
-              corepack disable
-              echo '::endgroup::'
+              exec_with_debug corepack disable
             fi
 
-            readonly npmSemver="${packageManager##npm@}"
-            echo "required-npm-version=${npmSemver%%+*}" >> "${GITHUB_ENV}"
-          else
+            exec_with_debug npm install --global --force "${packageManager%%+*}"
+
+            if [[ '${{ runner.os }}' == 'Windows' ]]; then
+              # Windows installs global packages to a directory that has lower priority than the default node install so we also need to edit $PATH
+              # see https://github.com/vercel/turbo/pull/1632/files#diff-b92a3120126a9ffe46d7d5ec3a8496ef1eac951db09e1972fac7c78438e36c42R69
+              echo '[command]' npm config get prefix '>>' "\$GITHUB_PATH"
+              npm config get prefix >> "${GITHUB_PATH}"
+            fi
+
+            echo '::endgroup::'
+          elif type corepack >/dev/null 2>&1; then
             # Old Corepack throws ENOTEMPTY errors (or EPERM errors on Windows) when running package managers in parallel.
             # This has been fixed in Corepack v0.11, so if the old Corepack is detected, this will be updated.
             # see https://github.com/nodejs/corepack/issues/110
@@ -174,10 +220,11 @@ jobs:
               } | grep -Eq '\b(ENOTEMPTY: directory not empty|EPERM: operation not permitted), rename\b'
             ); then
               echo '::group::' Old Corepack is detected "( corepack@$(corepack --version 2>/dev/null || echo '[Execution failed; Unknown version]') )". Update this
-              npm install --global --force 'corepack@0.11.2'
+              exec_with_debug npm install --global --force 'corepack@0.11.2'
               if [[ '${{ runner.os }}' == 'Windows' ]]; then
                 # Windows installs global packages to a directory that has lower priority than the default node install so we also need to edit $PATH
                 # see https://github.com/vercel/turbo/pull/1632/files#diff-b92a3120126a9ffe46d7d5ec3a8496ef1eac951db09e1972fac7c78438e36c42R69
+                echo '[command]' npm config get prefix '>>' "\$GITHUB_PATH"
                 npm config get prefix >> "${GITHUB_PATH}"
               fi
               echo '::endgroup::'
@@ -190,19 +237,8 @@ jobs:
             :
           else
             echo '::group::' Install yarn
-            npm install --global --force 'yarn@1.x'
+            exec_with_debug npm install --global --force 'yarn@1.x'
             echo '::endgroup::'
-          fi
-
-      - name: Update to the specified npm
-        if: ${{ env.required-npm-version }}
-        shell: bash
-        run: |
-          npm install --global --force 'npm@${{ env.required-npm-version }}'
-          if [[ '${{ runner.os }}' == 'Windows' ]]; then
-            # Windows installs global packages to a directory that has lower priority than the default node install so we also need to edit $PATH
-            # see https://github.com/vercel/turbo/pull/1632/files#diff-b92a3120126a9ffe46d7d5ec3a8496ef1eac951db09e1972fac7c78438e36c42R69
-            npm config get prefix >> "${GITHUB_PATH}"
           fi
 
       - name: Show node and npm version
