💚 [Debug] Try to switch package managers using Corepack in all Node.js

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -64,43 +64,43 @@ jobs:
       - id: detector
         uses: sounisi5011/npm-packages@actions/get-nodejs-versions-array-v0
 
-  lint:
-    needs: if-run-ci
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
+  # lint:
+  #   needs: if-run-ci
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Reconfigure git to use HTTP authentication
-        # see https://stackoverflow.com/a/69634516
-        # see https://github.com/actions/setup-node/issues/214#issuecomment-810829250
-        shell: bash
-        run: |
-          git config --global \
-            'url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf' \
-            'ssh://git@github.com/'
+  #     - name: Reconfigure git to use HTTP authentication
+  #       # see https://stackoverflow.com/a/69634516
+  #       # see https://github.com/actions/setup-node/issues/214#issuecomment-810829250
+  #       shell: bash
+  #       run: |
+  #         git config --global \
+  #           'url.https://${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf' \
+  #           'ssh://git@github.com/'
 
-      - name: Install Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 14.x
-          cache: npm
+  #     - name: Install Node.js
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 14.x
+  #         cache: npm
 
-      - name: Enable Corepack (Automatically setup a package manager for Node.js)
-        run: |
-          corepack enable
-          corepack enable npm
+  #     - name: Enable Corepack (Automatically setup a package manager for Node.js)
+  #       run: |
+  #         corepack enable
+  #         corepack enable npm
 
-      - name: Show node and npm version
-        shell: bash
-        run: |
-          echo node "$(node --version)"
-          echo npm "$(npm --version)"
+  #     - name: Show node and npm version
+  #       shell: bash
+  #       run: |
+  #         echo node "$(node --version)"
+  #         echo npm "$(npm --version)"
 
-      - name: Install dependencies
-        run: npm ci
+  #     - name: Install dependencies
+  #       run: npm ci
 
-      - name: Run linter
-        run: npm run test:other-than-unit-test
+  #     - name: Run linter
+  #       run: npm run test:other-than-unit-test
 
   unit-test:
     needs: detect-supported-node
@@ -232,6 +232,8 @@ jobs:
               npm_install_global 'corepack@0.11.2'
               echo '::endgroup::'
             fi
+
+            echo "corepack_available=1" >> "${GITHUB_ENV}"
           fi
 
           # If yarn is not available, install it
@@ -260,23 +262,23 @@ jobs:
   # So we can simplify our GitHub status check configuration.
   # see https://github.com/orgs/community/discussions/26822
   # see https://github.com/sounisi5011/npm-packages/blob/2a5ca2de696eeb8b40a38de90580441c4c6c96e0/.github/workflows/ci.yaml#L482-L498
-  complete:
-    name: Complete CI
-    needs: [lint, unit-test]
-    if:
-      ${{ always() && github.event.pull_request }}
-      # This job is required only for Pull Requests.
-      # It does not need to be run on other branches.
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check all job status
-        # see https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
-        # see https://docs.github.com/en/actions/learn-github-actions/expressions#contains
-        # see https://stackoverflow.com/a/67532120/4907315
-        if: >-
-          ${{
-               contains(needs.*.result, 'failure')
-            || contains(needs.*.result, 'cancelled')
-            || contains(needs.*.result, 'skipped')
-          }}
-        run: exit 1
+  # complete:
+  #   name: Complete CI
+  #   needs: [lint, unit-test]
+  #   if:
+  #     ${{ always() && github.event.pull_request }}
+  #     # This job is required only for Pull Requests.
+  #     # It does not need to be run on other branches.
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check all job status
+  #       # see https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
+  #       # see https://docs.github.com/en/actions/learn-github-actions/expressions#contains
+  #       # see https://stackoverflow.com/a/67532120/4907315
+  #       if: >-
+  #         ${{
+  #              contains(needs.*.result, 'failure')
+  #           || contains(needs.*.result, 'cancelled')
+  #           || contains(needs.*.result, 'skipped')
+  #         }}
+  #       run: exit 1
