💚 Update old Corepack that throws ENOTEMPTY error
Old Corepack throws ENOTEMPTY error when running package managers in parallel.
This has been fixed in Corepack v0.11, so if the old Corepack is detected, this will be updated.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -157,6 +157,28 @@ jobs:
             readonly npmSemver="${packageManager##npm@}"
             echo "required-npm-version=${npmSemver%%+*}" >> "${GITHUB_ENV}"
           else
+            # Old Corepack throws ENOTEMPTY error when running package managers in parallel.
+            # This has been fixed in Corepack v0.11, so if the old Corepack is detected, this will be updated.
+            # see https://github.com/nodejs/corepack/issues/110
+            # see https://github.com/nodejs/corepack/pull/84
+            TEST_COREPACK_DIRPATH="$(mktemp -dt test-corepack-ENOTEMPTY-error)"
+            readonly TEST_COREPACK_DIRPATH
+            echo '{"packageManager":"yarn@1.22.19"}' > "${TEST_COREPACK_DIRPATH}/package.json"
+            if (
+              cd "${TEST_COREPACK_DIRPATH}" && \
+              {
+                yarn --version 2>&1 &
+                yarn --version 2>&1 &
+                yarn --version 2>&1 &
+                wait
+              } | grep -Fq ENOTEMPTY
+            ); then
+              echo '::group::' Old Corepack is detected "( corepack@$(corepack --version 2>/dev/null || echo '[Execution failed; Unknown version]') )". Update this
+              npm install --global --force 'corepack@0.11.2'
+              echo '::endgroup::'
+            fi
+            rm -rf "${TEST_COREPACK_DIRPATH}"
+
             echo "corepack_available=1" >> "${GITHUB_ENV}"
           fi
 
